/**
 * Planteles oficiales del Mundial 2026 — publicados por FIFA el 2 de junio de 2026.
 * El campo `team` debe coincidir con los nombres que devuelve TheSportsDB.
 */
export const PLAYERS_DATA: { name: string; team: string }[] = [
  // ── ARGENTINA (Grupo J) ────────────────────────────────────
  { name: "Emiliano Martinez", team: "Argentina" },
  { name: "Geronimo Rulli", team: "Argentina" },
  { name: "Juan Musso", team: "Argentina" },
  { name: "Leonardo Balerdi", team: "Argentina" },
  { name: "Gonzalo Montiel", team: "Argentina" },
  { name: "Nicolas Tagliafico", team: "Argentina" },
  { name: "Lisandro Martinez", team: "Argentina" },
  { name: "Cristian Romero", team: "Argentina" },
  { name: "Nicolas Otamendi", team: "Argentina" },
  { name: "Facundo Medina", team: "Argentina" },
  { name: "Nahuel Molina", team: "Argentina" },
  { name: "Leandro Paredes", team: "Argentina" },
  { name: "Rodrigo De Paul", team: "Argentina" },
  { name: "Valentin Barco", team: "Argentina" },
  { name: "Giovani Lo Celso", team: "Argentina" },
  { name: "Exequiel Palacios", team: "Argentina" },
  { name: "Alexis Mac Allister", team: "Argentina" },
  { name: "Enzo Fernandez", team: "Argentina" },
  { name: "Julian Alvarez", team: "Argentina" },
  { name: "Lionel Messi", team: "Argentina" },
  { name: "Nicolas Gonzalez", team: "Argentina" },
  { name: "Thiago Almada", team: "Argentina" },
  { name: "Giuliano Simeone", team: "Argentina" },
  { name: "Nicolas Paz", team: "Argentina" },
  { name: "Jose Manuel Lopez", team: "Argentina" },
  { name: "Lautaro Martinez", team: "Argentina" },

  // ── AUSTRALIA (Grupo D) ────────────────────────────────────
  { name: "Patrick Beach", team: "Australia" },
  { name: "Paul Izzo", team: "Australia" },
  { name: "Mathew Ryan", team: "Australia" },
  { name: "Aziz Behich", team: "Australia" },
  { name: "Jordan Bos", team: "Australia" },
  { name: "Cameron Burgess", team: "Australia" },
  { name: "Alessandro Circati", team: "Australia" },
  { name: "Milos Degenek", team: "Australia" },
  { name: "Jason Geria", team: "Australia" },
  { name: "Lucas Herrington", team: "Australia" },
  { name: "Jacob Italiano", team: "Australia" },
  { name: "Harry Souttar", team: "Australia" },
  { name: "Kai Trewin", team: "Australia" },
  { name: "Cameron Devlin", team: "Australia" },
  { name: "Ajdin Hrustic", team: "Australia" },
  { name: "Jackson Irvine", team: "Australia" },
  { name: "Connor Metcalfe", team: "Australia" },
  { name: "Aiden O'Neill", team: "Australia" },
  { name: "Paul Okon-Engstler", team: "Australia" },
  { name: "Nestory Irankunda", team: "Australia" },
  { name: "Mathew Leckie", team: "Australia" },
  { name: "Awer Mabil", team: "Australia" },
  { name: "Mohamed Toure", team: "Australia" },
  { name: "Nishan Velupillay", team: "Australia" },
  { name: "Cristian Volpato", team: "Australia" },
  { name: "Tete Yengi", team: "Australia" },

  // ── AUSTRIA (Grupo J) ──────────────────────────────────────
  { name: "Patrick Pentz", team: "Austria" },
  { name: "Alexander Schlager", team: "Austria" },
  { name: "Florian Wiegele", team: "Austria" },
  { name: "David Affengruber", team: "Austria" },
  { name: "David Alaba", team: "Austria" },
  { name: "Kevin Danso", team: "Austria" },
  { name: "Marco Friedl", team: "Austria" },
  { name: "Philipp Lienhart", team: "Austria" },
  { name: "Phillipp Mwene", team: "Austria" },
  { name: "Stefan Posch", team: "Austria" },
  { name: "Alexander Prass", team: "Austria" },
  { name: "Michael Svoboda", team: "Austria" },
  { name: "Christoph Baumgartner", team: "Austria" },
  { name: "Carney Chukwuemeka", team: "Austria" },
  { name: "Florian Grillitsch", team: "Austria" },
  { name: "Konrad Laimer", team: "Austria" },
  { name: "Marcel Sabitzer", team: "Austria" },
  { name: "Xaver Schlager", team: "Austria" },
  { name: "Romano Schmid", team: "Austria" },
  { name: "Alessandro Schopf", team: "Austria" },
  { name: "Nicolas Seiwald", team: "Austria" },
  { name: "Paul Wanner", team: "Austria" },
  { name: "Patrick Wimmer", team: "Austria" },
  { name: "Marko Arnautovic", team: "Austria" },
  { name: "Michael Gregoritsch", team: "Austria" },
  { name: "Sasa Kalajdzic", team: "Austria" },

  // ── BELGIUM (Grupo G) ──────────────────────────────────────
  { name: "Thibaut Courtois", team: "Belgium" },
  { name: "Senne Lammens", team: "Belgium" },
  { name: "Mike Penders", team: "Belgium" },
  { name: "Timothy Castagne", team: "Belgium" },
  { name: "Zeno Debast", team: "Belgium" },
  { name: "Maxim De Cuyper", team: "Belgium" },
  { name: "Koni De Winter", team: "Belgium" },
  { name: "Brandon Mechele", team: "Belgium" },
  { name: "Thomas Meunier", team: "Belgium" },
  { name: "Nathan Ngoy", team: "Belgium" },
  { name: "Joaquin Seys", team: "Belgium" },
  { name: "Arthur Theate", team: "Belgium" },
  { name: "Kevin De Bruyne", team: "Belgium" },
  { name: "Amadou Onana", team: "Belgium" },
  { name: "Nicolas Raskin", team: "Belgium" },
  { name: "Youri Tielemans", team: "Belgium" },
  { name: "Hans Vanaken", team: "Belgium" },
  { name: "Axel Witsel", team: "Belgium" },
  { name: "Charles De Ketelaere", team: "Belgium" },
  { name: "Jeremy Doku", team: "Belgium" },
  { name: "Matias Fernandez-Pardo", team: "Belgium" },
  { name: "Romelu Lukaku", team: "Belgium" },
  { name: "Dodi Lukebakio", team: "Belgium" },
  { name: "Diego Moreira", team: "Belgium" },
  { name: "Alexis Saelemaekers", team: "Belgium" },
  { name: "Leandro Trossard", team: "Belgium" },

  // ── BOSNIA AND HERZEGOVINA (Grupo B) ──────────────────────
  { name: "Nikola Vasilj", team: "Bosnia-Herzegovina" },
  { name: "Martin Zlomislic", team: "Bosnia-Herzegovina" },
  { name: "Osman Hadzikic", team: "Bosnia-Herzegovina" },
  { name: "Sead Kolasinac", team: "Bosnia-Herzegovina" },
  { name: "Amar Dedic", team: "Bosnia-Herzegovina" },
  { name: "Nihad Mujakic", team: "Bosnia-Herzegovina" },
  { name: "Nikola Katic", team: "Bosnia-Herzegovina" },
  { name: "Tarik Muharemovic", team: "Bosnia-Herzegovina" },
  { name: "Stjepan Radeljic", team: "Bosnia-Herzegovina" },
  { name: "Dennis Hadzikadunic", team: "Bosnia-Herzegovina" },
  { name: "Nidal Celik", team: "Bosnia-Herzegovina" },
  { name: "Amir Hadziahmetovic", team: "Bosnia-Herzegovina" },
  { name: "Ivan Sunjic", team: "Bosnia-Herzegovina" },
  { name: "Ivan Basic", team: "Bosnia-Herzegovina" },
  { name: "Dzenis Burnic", team: "Bosnia-Herzegovina" },
  { name: "Ermin Mahmic", team: "Bosnia-Herzegovina" },
  { name: "Benjamin Tahirovic", team: "Bosnia-Herzegovina" },
  { name: "Amar Memic", team: "Bosnia-Herzegovina" },
  { name: "Armin Gigovic", team: "Bosnia-Herzegovina" },
  { name: "Kerim Alajbegovic", team: "Bosnia-Herzegovina" },
  { name: "Esmir Bajraktarevic", team: "Bosnia-Herzegovina" },
  { name: "Ermedin Demirovic", team: "Bosnia-Herzegovina" },
  { name: "Jovo Lukic", team: "Bosnia-Herzegovina" },
  { name: "Samed Bazdar", team: "Bosnia-Herzegovina" },
  { name: "Haris Tabakovic", team: "Bosnia-Herzegovina" },
  { name: "Edin Dzeko", team: "Bosnia-Herzegovina" },

  // ── BRAZIL (Grupo C) ───────────────────────────────────────
  { name: "Alisson", team: "Brazil" },
  { name: "Ederson", team: "Brazil" },
  { name: "Weverton", team: "Brazil" },
  { name: "Alex Sandro", team: "Brazil" },
  { name: "Bremer", team: "Brazil" },
  { name: "Danilo", team: "Brazil" },
  { name: "Douglas Santos", team: "Brazil" },
  { name: "Gabriel Magalhaes", team: "Brazil" },
  { name: "Ibanez", team: "Brazil" },
  { name: "Leo Pereira", team: "Brazil" },
  { name: "Marquinhos", team: "Brazil" },
  { name: "Wesley", team: "Brazil" },
  { name: "Bruno Guimaraes", team: "Brazil" },
  { name: "Casemiro", team: "Brazil" },
  { name: "Danilo Santos", team: "Brazil" },
  { name: "Fabinho", team: "Brazil" },
  { name: "Lucas Paqueta", team: "Brazil" },
  { name: "Endrick", team: "Brazil" },
  { name: "Gabriel Martinelli", team: "Brazil" },
  { name: "Igor Thiago", team: "Brazil" },
  { name: "Luiz Henrique", team: "Brazil" },
  { name: "Matheus Cunha", team: "Brazil" },
  { name: "Neymar Jr", team: "Brazil" },
  { name: "Raphinha", team: "Brazil" },
  { name: "Rayan", team: "Brazil" },
  { name: "Vinicius Jr.", team: "Brazil" },

  // ── CANADA (Grupo B) ───────────────────────────────────────
  { name: "Dayne St Clair", team: "Canada" },
  { name: "Maxime Crepeau", team: "Canada" },
  { name: "Owen Goodman", team: "Canada" },
  { name: "Alistair Johnston", team: "Canada" },
  { name: "Derek Cornelius", team: "Canada" },
  { name: "Richie Laryea", team: "Canada" },
  { name: "Niko Sigur", team: "Canada" },
  { name: "Joel Waterman", team: "Canada" },
  { name: "Luc de Fougerolles", team: "Canada" },
  { name: "Moise Bombito", team: "Canada" },
  { name: "Alphonso Davies", team: "Canada" },
  { name: "Alfie Jones", team: "Canada" },
  { name: "Stephen Eustaquio", team: "Canada" },
  { name: "Ismael Kone", team: "Canada" },
  { name: "Tajon Buchanan", team: "Canada" },
  { name: "Mathieu Choiniere", team: "Canada" },
  { name: "Ali Ahmed", team: "Canada" },
  { name: "Nathan Saliba", team: "Canada" },
  { name: "Liam Millar", team: "Canada" },
  { name: "Jacob Shaffelburg", team: "Canada" },
  { name: "Jonathan Osorio", team: "Canada" },
  { name: "Jonathan David", team: "Canada" },
  { name: "Cyle Larin", team: "Canada" },
  { name: "Tani Oluwaseyi", team: "Canada" },
  { name: "Promise David", team: "Canada" },

  // ── CAPE VERDE (Grupo H) ───────────────────────────────────
  { name: "Vozinha", team: "Cape Verde" },
  { name: "Marcio Rosa", team: "Cape Verde" },
  { name: "CJ dos Santos", team: "Cape Verde" },
  { name: "Sidny Cabral", team: "Cape Verde" },
  { name: "Diney Borges", team: "Cape Verde" },
  { name: "Logan Costa", team: "Cape Verde" },
  { name: "Roberto Lopes", team: "Cape Verde" },
  { name: "Steven Moreira", team: "Cape Verde" },
  { name: "Wagner Pina", team: "Cape Verde" },
  { name: "Kelvin Pires", team: "Cape Verde" },
  { name: "Joao Paulo Fernandes", team: "Cape Verde" },
  { name: "Stopira", team: "Cape Verde" },
  { name: "Telmo Arcanjo", team: "Cape Verde" },
  { name: "Deroy Duarte", team: "Cape Verde" },
  { name: "Laros Duarte", team: "Cape Verde" },
  { name: "Jamiro Monteiro", team: "Cape Verde" },
  { name: "Kevin Pina", team: "Cape Verde" },
  { name: "Yannick Semedo", team: "Cape Verde" },
  { name: "Gilson Benchimol", team: "Cape Verde" },
  { name: "Jovane Cabral", team: "Cape Verde" },
  { name: "Dailon Livramento", team: "Cape Verde" },
  { name: "Ryan Mendes", team: "Cape Verde" },
  { name: "Nuno da Costa", team: "Cape Verde" },
  { name: "Garry Rodrigues", team: "Cape Verde" },
  { name: "Willy Semedo", team: "Cape Verde" },
  { name: "Helio Varela", team: "Cape Verde" },

  // ── COLOMBIA (Grupo K) ─────────────────────────────────────
  { name: "Camilo Vargas", team: "Colombia" },
  { name: "Alvaro Montero", team: "Colombia" },
  { name: "David Ospina", team: "Colombia" },
  { name: "Davinson Sanchez", team: "Colombia" },
  { name: "Jhon Lucumi", team: "Colombia" },
  { name: "Yerry Mina", team: "Colombia" },
  { name: "Willer Ditta", team: "Colombia" },
  { name: "Daniel Munoz", team: "Colombia" },
  { name: "Santiago Arias", team: "Colombia" },
  { name: "Johan Mojica", team: "Colombia" },
  { name: "Deiver Machado", team: "Colombia" },
  { name: "Richard Rios", team: "Colombia" },
  { name: "Jefferson Lerma", team: "Colombia" },
  { name: "Kevin Castano", team: "Colombia" },
  { name: "Juan Camilo Portilla", team: "Colombia" },
  { name: "Gustavo Puerta", team: "Colombia" },
  { name: "Jhon Arias", team: "Colombia" },
  { name: "Jorge Carrascal", team: "Colombia" },
  { name: "Juan Fernando Quintero", team: "Colombia" },
  { name: "James Rodriguez", team: "Colombia" },
  { name: "Jaminton Campaz", team: "Colombia" },
  { name: "Juan Camilo Hernandez", team: "Colombia" },
  { name: "Luis Diaz", team: "Colombia" },
  { name: "Luis Suarez", team: "Colombia" },
  { name: "Carlos Gomez", team: "Colombia" },
  { name: "Jhon Cordoba", team: "Colombia" },

  // ── CROATIA (Grupo L) ──────────────────────────────────────
  { name: "Dominik Livakovic", team: "Croatia" },
  { name: "Dominik Kotarski", team: "Croatia" },
  { name: "Ivor Pandur", team: "Croatia" },
  { name: "Josko Gvardiol", team: "Croatia" },
  { name: "Duje Caleta-Car", team: "Croatia" },
  { name: "Josip Sutalo", team: "Croatia" },
  { name: "Josip Stanisic", team: "Croatia" },
  { name: "Marin Pongracic", team: "Croatia" },
  { name: "Martin Erlic", team: "Croatia" },
  { name: "Luka Vuskovic", team: "Croatia" },
  { name: "Luka Modric", team: "Croatia" },
  { name: "Mateo Kovacic", team: "Croatia" },
  { name: "Mario Pasalic", team: "Croatia" },
  { name: "Nikola Vlasic", team: "Croatia" },
  { name: "Luka Sucic", team: "Croatia" },
  { name: "Martin Baturina", team: "Croatia" },
  { name: "Kristijan Jakic", team: "Croatia" },
  { name: "Petar Sucic", team: "Croatia" },
  { name: "Nikola Moro", team: "Croatia" },
  { name: "Toni Fruk", team: "Croatia" },
  { name: "Ivan Perisic", team: "Croatia" },
  { name: "Andrej Kramaric", team: "Croatia" },
  { name: "Ante Budimir", team: "Croatia" },
  { name: "Marco Pasalic", team: "Croatia" },
  { name: "Petar Musa", team: "Croatia" },
  { name: "Igor Matanovic", team: "Croatia" },

  // ── CURACAO (Grupo E) ──────────────────────────────────────
  { name: "Tyrick Bodack", team: "Curacao" },
  { name: "Trevor Doornbusch", team: "Curacao" },
  { name: "Eloy Room", team: "Curacao" },
  { name: "Riechedly Bazoer", team: "Curacao" },
  { name: "Joshua Brenet", team: "Curacao" },
  { name: "Roshon van Eijma", team: "Curacao" },
  { name: "Sherel Floranus", team: "Curacao" },
  { name: "Deveron Fonville", team: "Curacao" },
  { name: "Jurien Gaari", team: "Curacao" },
  { name: "Armando Obispo", team: "Curacao" },
  { name: "Shurandy Sambo", team: "Curacao" },
  { name: "Juninho Bacuna", team: "Curacao" },
  { name: "Leandro Bacuna", team: "Curacao" },
  { name: "Livano Comenencia", team: "Curacao" },
  { name: "Kevin Felida", team: "Curacao" },
  { name: "Ar'jany Martha", team: "Curacao" },
  { name: "Tyrese Noslin", team: "Curacao" },
  { name: "Godfried Roemeratoe", team: "Curacao" },
  { name: "Jeremy Antonisse", team: "Curacao" },
  { name: "Tahith Chong", team: "Curacao" },
  { name: "Kenji Gorre", team: "Curacao" },
  { name: "Sontje Hansen", team: "Curacao" },
  { name: "Gervane Kastaneer", team: "Curacao" },
  { name: "Brandley Kuwas", team: "Curacao" },
  { name: "Jurgen Locadia", team: "Curacao" },
  { name: "Jearl Margaritha", team: "Curacao" },

  // ── CZECHIA (Grupo A) ──────────────────────────────────────
  { name: "Lukas Hornicek", team: "Czechia" },
  { name: "Matej Kovar", team: "Czechia" },
  { name: "Jindrich Stanek", team: "Czechia" },
  { name: "Vladimir Coufal", team: "Czechia" },
  { name: "David Doudera", team: "Czechia" },
  { name: "Tomas Holes", team: "Czechia" },
  { name: "Robin Hranac", team: "Czechia" },
  { name: "Stepan Chaloupek", team: "Czechia" },
  { name: "David Jurasek", team: "Czechia" },
  { name: "Ladislav Krejci", team: "Czechia" },
  { name: "Jaroslav Zeleny", team: "Czechia" },
  { name: "David Zima", team: "Czechia" },
  { name: "Lukas Cerv", team: "Czechia" },
  { name: "Vladimir Darida", team: "Czechia" },
  { name: "Lukas Provod", team: "Czechia" },
  { name: "Michal Sadilek", team: "Czechia" },
  { name: "Hugo Sochurek", team: "Czechia" },
  { name: "Alexandr Sojka", team: "Czechia" },
  { name: "Tomas Soucek", team: "Czechia" },
  { name: "Denis Visinsky", team: "Czechia" },
  { name: "Adam Hlozek", team: "Czechia" },
  { name: "Tomas Chory", team: "Czechia" },
  { name: "Mojmir Chytil", team: "Czechia" },
  { name: "Jan Kuchta", team: "Czechia" },
  { name: "Patrik Schick", team: "Czechia" },

  // ── DR CONGO (Grupo K) ─────────────────────────────────────
  { name: "Matthieu Epolo", team: "DR Congo" },
  { name: "Timothy Fayulu", team: "DR Congo" },
  { name: "Lionel Mpasi", team: "DR Congo" },
  { name: "Dylan Batubinsika", team: "DR Congo" },
  { name: "Gedeon Kalulu", team: "DR Congo" },
  { name: "Steve Kapuadi", team: "DR Congo" },
  { name: "Joris Kayembe", team: "DR Congo" },
  { name: "Arthur Masuaku", team: "DR Congo" },
  { name: "Chancel Mbemba", team: "DR Congo" },
  { name: "Axel Tuanzebe", team: "DR Congo" },
  { name: "Aaron Wan-Bissaka", team: "DR Congo" },
  { name: "Brian Cipenga", team: "DR Congo" },
  { name: "Meshack Elia", team: "DR Congo" },
  { name: "Gael Kakuta", team: "DR Congo" },
  { name: "Edo Kayembe", team: "DR Congo" },
  { name: "Nathanael Mbuku", team: "DR Congo" },
  { name: "Samuel Moutoussamy", team: "DR Congo" },
  { name: "Ngal'ayel Mukau", team: "DR Congo" },
  { name: "Charles Pickel", team: "DR Congo" },
  { name: "Noah Sadiki", team: "DR Congo" },
  { name: "Aaron Tshibola", team: "DR Congo" },
  { name: "Cedric Bakambu", team: "DR Congo" },
  { name: "Simon Banza", team: "DR Congo" },
  { name: "Fiston Mayele", team: "DR Congo" },
  { name: "Yoane Wissa", team: "DR Congo" },
  { name: "Theo Bongonda", team: "DR Congo" },

  // ── ECUADOR (Grupo E) ──────────────────────────────────────
  { name: "Hernan Galindez", team: "Ecuador" },
  { name: "Moises Ramirez", team: "Ecuador" },
  { name: "Gonzalo Valle", team: "Ecuador" },
  { name: "Piero Hincapie", team: "Ecuador" },
  { name: "Willian Pacho", team: "Ecuador" },
  { name: "Pervis Estupinan", team: "Ecuador" },
  { name: "Felix Torres", team: "Ecuador" },
  { name: "Joel Ordonez", team: "Ecuador" },
  { name: "Jackson Porozo", team: "Ecuador" },
  { name: "Angelo Preciado", team: "Ecuador" },
  { name: "Yaimar Medina", team: "Ecuador" },
  { name: "Moises Caicedo", team: "Ecuador" },
  { name: "Alan Franco", team: "Ecuador" },
  { name: "Kendry Paez", team: "Ecuador" },
  { name: "Gonzalo Plata", team: "Ecuador" },
  { name: "Pedro Vite", team: "Ecuador" },
  { name: "Jordy Alcivar", team: "Ecuador" },
  { name: "Denil Castillo", team: "Ecuador" },
  { name: "John Yeboah", team: "Ecuador" },
  { name: "Nilson Angulo", team: "Ecuador" },
  { name: "Alan Minda", team: "Ecuador" },
  { name: "Enner Valencia", team: "Ecuador" },
  { name: "Kevin Rodriguez", team: "Ecuador" },
  { name: "Jordy Caicedo", team: "Ecuador" },
  { name: "Anthony Valencia", team: "Ecuador" },
  { name: "Jeremy Arevalo", team: "Ecuador" },

  // ── EGYPT (Grupo G) ────────────────────────────────────────
  { name: "Mohamed El Shenawy", team: "Egypt" },
  { name: "Mostafa Shobeir", team: "Egypt" },
  { name: "El Mahdy Soliman", team: "Egypt" },
  { name: "Mohamed Alaa", team: "Egypt" },
  { name: "Mohamed Abdelmonem", team: "Egypt" },
  { name: "Mohamed Hany", team: "Egypt" },
  { name: "Yasser Ibrahim", team: "Egypt" },
  { name: "Hossam Abdelmaguid", team: "Egypt" },
  { name: "Ahmed Fattouh", team: "Egypt" },
  { name: "Tarek Alaa", team: "Egypt" },
  { name: "Rami Rabia", team: "Egypt" },
  { name: "Karim Hafez", team: "Egypt" },
  { name: "Marwan Attia", team: "Egypt" },
  { name: "Ahmed Sayed Zizo", team: "Egypt" },
  { name: "Mahmoud Trezeguet", team: "Egypt" },
  { name: "Emam Ashour", team: "Egypt" },
  { name: "Mostafa Abdel Raouf", team: "Egypt" },
  { name: "Mohannad Lasheen", team: "Egypt" },
  { name: "Haitham Hassan", team: "Egypt" },
  { name: "Ibrahim Adel", team: "Egypt" },
  { name: "Hamdi Fathi", team: "Egypt" },
  { name: "Mohamed Salah", team: "Egypt" },
  { name: "Omar Marmoush", team: "Egypt" },
  { name: "Hamza Abdel Karim", team: "Egypt" },

  // ── ENGLAND (Grupo L) ──────────────────────────────────────
  { name: "Jordan Pickford", team: "England" },
  { name: "Dean Henderson", team: "England" },
  { name: "James Trafford", team: "England" },
  { name: "Reece James", team: "England" },
  { name: "Ezri Konsa", team: "England" },
  { name: "Jarell Quansah", team: "England" },
  { name: "John Stones", team: "England" },
  { name: "Marc Guehi", team: "England" },
  { name: "Dan Burn", team: "England" },
  { name: "Nico O'Reilly", team: "England" },
  { name: "Djed Spence", team: "England" },
  { name: "Tino Livramento", team: "England" },
  { name: "Declan Rice", team: "England" },
  { name: "Elliot Anderson", team: "England" },
  { name: "Kobbie Mainoo", team: "England" },
  { name: "Jordan Henderson", team: "England" },
  { name: "Morgan Rogers", team: "England" },
  { name: "Jude Bellingham", team: "England" },
  { name: "Eberechi Eze", team: "England" },
  { name: "Harry Kane", team: "England" },
  { name: "Ivan Toney", team: "England" },
  { name: "Ollie Watkins", team: "England" },
  { name: "Bukayo Saka", team: "England" },
  { name: "Marcus Rashford", team: "England" },
  { name: "Anthony Gordon", team: "England" },
  { name: "Noni Madueke", team: "England" },

  // ── FRANCE (Grupo I) ───────────────────────────────────────
  { name: "Mike Maignan", team: "France" },
  { name: "Robin Risser", team: "France" },
  { name: "Brice Samba", team: "France" },
  { name: "Lucas Digne", team: "France" },
  { name: "Malo Gusto", team: "France" },
  { name: "Lucas Hernandez", team: "France" },
  { name: "Theo Hernandez", team: "France" },
  { name: "Ibrahima Konate", team: "France" },
  { name: "Maxence Lacroix", team: "France" },
  { name: "Jules Kounde", team: "France" },
  { name: "William Saliba", team: "France" },
  { name: "Dayot Upamecano", team: "France" },
  { name: "N'Golo Kante", team: "France" },
  { name: "Manu Kone", team: "France" },
  { name: "Adrien Rabiot", team: "France" },
  { name: "Aurelien Tchouameni", team: "France" },
  { name: "Warren Zaire-Emery", team: "France" },
  { name: "Maghnes Akliouche", team: "France" },
  { name: "Bradley Barcola", team: "France" },
  { name: "Rayan Cherki", team: "France" },
  { name: "Ousmane Dembele", team: "France" },
  { name: "Desire Doue", team: "France" },
  { name: "Michael Olise", team: "France" },
  { name: "Kylian Mbappe", team: "France" },
  { name: "Jean-Philippe Mateta", team: "France" },
  { name: "Marcus Thuram", team: "France" },

  // ── GERMANY (Grupo E) ──────────────────────────────────────
  { name: "Manuel Neuer", team: "Germany" },
  { name: "Oliver Baumann", team: "Germany" },
  { name: "Alexander Nuebel", team: "Germany" },
  { name: "Nico Schlotterbeck", team: "Germany" },
  { name: "David Raum", team: "Germany" },
  { name: "Nathaniel Brown", team: "Germany" },
  { name: "Jonathan Tah", team: "Germany" },
  { name: "Waldemar Anton", team: "Germany" },
  { name: "Joshua Kimmich", team: "Germany" },
  { name: "Malick Thiaw", team: "Germany" },
  { name: "Antonio Rudiger", team: "Germany" },
  { name: "Pascal Gross", team: "Germany" },
  { name: "Leon Goretzka", team: "Germany" },
  { name: "Felix Nmecha", team: "Germany" },
  { name: "Jamal Musiala", team: "Germany" },
  { name: "Nadiem Amiri", team: "Germany" },
  { name: "Jamie Leweling", team: "Germany" },
  { name: "Lennart Karl", team: "Germany" },
  { name: "Florian Wirtz", team: "Germany" },
  { name: "Leroy Sane", team: "Germany" },
  { name: "Aleksandar Pavlovic", team: "Germany" },
  { name: "Angelo Stiller", team: "Germany" },
  { name: "Kai Havertz", team: "Germany" },
  { name: "Nick Woltemade", team: "Germany" },
  { name: "Deniz Undav", team: "Germany" },
  { name: "Maximilian Beier", team: "Germany" },

  // ── GHANA (Grupo L) ────────────────────────────────────────
  { name: "Joseph Anang", team: "Ghana" },
  { name: "Benjamin Asare", team: "Ghana" },
  { name: "Lawrence Ati-Zigi", team: "Ghana" },
  { name: "Jonas Adjetey", team: "Ghana" },
  { name: "Derrick Luckassen", team: "Ghana" },
  { name: "Gideon Mensah", team: "Ghana" },
  { name: "Abdul Mumin", team: "Ghana" },
  { name: "Jerome Opoku", team: "Ghana" },
  { name: "Kojo Oppong Preprah", team: "Ghana" },
  { name: "Baba Abdul Rahman", team: "Ghana" },
  { name: "Alidu Seidu", team: "Ghana" },
  { name: "Marvin Senaya", team: "Ghana" },
  { name: "Augustine Boakye", team: "Ghana" },
  { name: "Abdul Fatawu Issahaku", team: "Ghana" },
  { name: "Elisha Owusu", team: "Ghana" },
  { name: "Thomas Partey", team: "Ghana" },
  { name: "Kwasi Sibo", team: "Ghana" },
  { name: "Kamal Deen Sulemana", team: "Ghana" },
  { name: "Caleb Yirenkyi", team: "Ghana" },
  { name: "Jordan Ayew", team: "Ghana" },
  { name: "Christopher Bonsu Baah", team: "Ghana" },
  { name: "Ernest Nuamah", team: "Ghana" },
  { name: "Antoine Semenyo", team: "Ghana" },
  { name: "Brandon Thomas-Asante", team: "Ghana" },
  { name: "Inaki Williams", team: "Ghana" },

  // ── HAITI (Grupo C) ────────────────────────────────────────
  { name: "Josue Duverger", team: "Haiti" },
  { name: "Alexandre Pierre", team: "Haiti" },
  { name: "Johny Placide", team: "Haiti" },
  { name: "Ricardo Ade", team: "Haiti" },
  { name: "Carlens Arcus", team: "Haiti" },
  { name: "Hannes Delcroix", team: "Haiti" },
  { name: "Jean-Kevin Duverne", team: "Haiti" },
  { name: "Martin Experience", team: "Haiti" },
  { name: "Duke Lacroix", team: "Haiti" },
  { name: "Wilguens Paugain", team: "Haiti" },
  { name: "Keeto Thermoncy", team: "Haiti" },
  { name: "Carl Fred Sainte", team: "Haiti" },
  { name: "Jean-Ricner Bellegarde", team: "Haiti" },
  { name: "Leverton Pierre", team: "Haiti" },
  { name: "Danley Jean Jacques", team: "Haiti" },
  { name: "Woodensky Pierre", team: "Haiti" },
  { name: "Dominique Simon", team: "Haiti" },
  { name: "Josue Casimir", team: "Haiti" },
  { name: "Derrick Etienne Jr.", team: "Haiti" },
  { name: "Yassin Fortune", team: "Haiti" },
  { name: "Wilson Isidor", team: "Haiti" },
  { name: "Lenny Joseph", team: "Haiti" },
  { name: "Duckens Nazon", team: "Haiti" },
  { name: "Frantzdy Pierrot", team: "Haiti" },
  { name: "Ruben Providence", team: "Haiti" },

  // ── IRAN (Grupo G) ─────────────────────────────────────────
  { name: "Alireza Beiranvand", team: "Iran" },
  { name: "Hossein Hosseini", team: "Iran" },
  { name: "Payam Niazmand", team: "Iran" },
  { name: "Danial Eiri", team: "Iran" },
  { name: "Ehsan Hajsafi", team: "Iran" },
  { name: "Saleh Hardani", team: "Iran" },
  { name: "Hossein Kanaani", team: "Iran" },
  { name: "Shoja Khalilzadeh", team: "Iran" },
  { name: "Milad Mohammadi", team: "Iran" },
  { name: "Ali Nemati", team: "Iran" },
  { name: "Ramin Rezaeian", team: "Iran" },
  { name: "Rouzbeh Cheshmi", team: "Iran" },
  { name: "Saeid Ezatolahi", team: "Iran" },
  { name: "Mehdi Ghaedi", team: "Iran" },
  { name: "Saman Ghoddos", team: "Iran" },
  { name: "Mohammad Ghorbani", team: "Iran" },
  { name: "Alireza Jahanbakhsh", team: "Iran" },
  { name: "Mohammad Mohebi", team: "Iran" },
  { name: "Amir Mohammad Razzaghinia", team: "Iran" },
  { name: "Mehdi Torabi", team: "Iran" },
  { name: "Aria Yousefi", team: "Iran" },
  { name: "Ali Alipour", team: "Iran" },
  { name: "Dennis Dargahi", team: "Iran" },
  { name: "Amirhossein Hosseinzadeh", team: "Iran" },
  { name: "Mehdi Taremi", team: "Iran" },
  { name: "Shahriar Moghanlou", team: "Iran" },

  // ── IRAQ (Grupo I) ─────────────────────────────────────────
  { name: "Fahad Talib", team: "Iraq" },
  { name: "Jalal Hassan", team: "Iraq" },
  { name: "Ahmed Basil", team: "Iraq" },
  { name: "Hussein Ali", team: "Iraq" },
  { name: "Manaf Younis", team: "Iraq" },
  { name: "Zaid Tahseen", team: "Iraq" },
  { name: "Rebin Sulaka", team: "Iraq" },
  { name: "Akam Hashem", team: "Iraq" },
  { name: "Merchas Doski", team: "Iraq" },
  { name: "Ahmed Yahya", team: "Iraq" },
  { name: "Zaid Ismail", team: "Iraq" },
  { name: "Frans Putros", team: "Iraq" },
  { name: "Mustafa Saadoon", team: "Iraq" },
  { name: "Amir Al Ammari", team: "Iraq" },
  { name: "Kevin Yakob", team: "Iraq" },
  { name: "Zidane Iqbal", team: "Iraq" },
  { name: "Aimar Sher", team: "Iraq" },
  { name: "Ibrahim Bayesh", team: "Iraq" },
  { name: "Ahmed Qasim", team: "Iraq" },
  { name: "Youssef Amyn", team: "Iraq" },
  { name: "Marko Farji", team: "Iraq" },
  { name: "Ali Jassim", team: "Iraq" },
  { name: "Ali Al Hamadi", team: "Iraq" },
  { name: "Ali Yousef", team: "Iraq" },
  { name: "Aymen Hussein", team: "Iraq" },
  { name: "Mohanad Ali", team: "Iraq" },

  // ── IVORY COAST (Grupo E) ──────────────────────────────────
  { name: "Yahia Fofana", team: "Ivory Coast" },
  { name: "Mohamed Kone", team: "Ivory Coast" },
  { name: "Alban Lafont", team: "Ivory Coast" },
  { name: "Emmanuel Agbadou", team: "Ivory Coast" },
  { name: "Christopher Operi", team: "Ivory Coast" },
  { name: "Ousmane Diomande", team: "Ivory Coast" },
  { name: "Guela Doue", team: "Ivory Coast" },
  { name: "Ghislain Konan", team: "Ivory Coast" },
  { name: "Odilon Kossounou", team: "Ivory Coast" },
  { name: "Wilfried Singo", team: "Ivory Coast" },
  { name: "Evan Ndicka", team: "Ivory Coast" },
  { name: "Seko Fofana", team: "Ivory Coast" },
  { name: "Parfait Guiagon", team: "Ivory Coast" },
  { name: "Franck Kessie", team: "Ivory Coast" },
  { name: "Ibrahim Sangare", team: "Ivory Coast" },
  { name: "Jean Michael Seri", team: "Ivory Coast" },
  { name: "Simon Adingra", team: "Ivory Coast" },
  { name: "Ange-Yoan Bonny", team: "Ivory Coast" },
  { name: "Amad Diallo", team: "Ivory Coast" },
  { name: "Oumar Diakite", team: "Ivory Coast" },
  { name: "Yan Diomande", team: "Ivory Coast" },
  { name: "Evann Guessand", team: "Ivory Coast" },
  { name: "Nicolas Pepe", team: "Ivory Coast" },
  { name: "Bazoumana Toure", team: "Ivory Coast" },
  { name: "Elye Wahi", team: "Ivory Coast" },

  // ── JAPAN (Grupo F) ────────────────────────────────────────
  { name: "Tomoki Hayakawa", team: "Japan" },
  { name: "Keisuke Osako", team: "Japan" },
  { name: "Zion Suzuki", team: "Japan" },
  { name: "Ko Itakura", team: "Japan" },
  { name: "Hiroki Ito", team: "Japan" },
  { name: "Yuto Nagatomo", team: "Japan" },
  { name: "Ayumu Seko", team: "Japan" },
  { name: "Yukinari Sugawara", team: "Japan" },
  { name: "Junnosuke Suzuki", team: "Japan" },
  { name: "Shogo Taniguchi", team: "Japan" },
  { name: "Takehiro Tomiyasu", team: "Japan" },
  { name: "Tsuyoshi Watanabe", team: "Japan" },
  { name: "Ritsu Doan", team: "Japan" },
  { name: "Wataru Endo", team: "Japan" },
  { name: "Junya Ito", team: "Japan" },
  { name: "Daichi Kamada", team: "Japan" },
  { name: "Takefusa Kubo", team: "Japan" },
  { name: "Keito Nakamura", team: "Japan" },
  { name: "Kaishu Sano", team: "Japan" },
  { name: "Ao Tanaka", team: "Japan" },
  { name: "Keisuke Goto", team: "Japan" },
  { name: "Daizen Maeda", team: "Japan" },
  { name: "Koki Ogawa", team: "Japan" },
  { name: "Kento Shiogai", team: "Japan" },
  { name: "Yuito Suzuki", team: "Japan" },
  { name: "Ayase Ueda", team: "Japan" },

  // ── JORDAN (Grupo J) ───────────────────────────────────────
  { name: "Yazid Abulaila", team: "Jordan" },
  { name: "Noor Bani Attiah", team: "Jordan" },
  { name: "Abdallah Al Fakhouri", team: "Jordan" },
  { name: "Mohammad Abu Hashish", team: "Jordan" },
  { name: "Abdullah Nasib", team: "Jordan" },
  { name: "Hussam Abu Dhahab", team: "Jordan" },
  { name: "Yazan Al Arab", team: "Jordan" },
  { name: "Mohammad Abu Alnadi", team: "Jordan" },
  { name: "Salem Obaid", team: "Jordan" },
  { name: "Saed Al Rosan", team: "Jordan" },
  { name: "Ehsan Haddad", team: "Jordan" },
  { name: "Anas Badawi", team: "Jordan" },
  { name: "Amer Jamous", team: "Jordan" },
  { name: "Noor Al Rawabdeh", team: "Jordan" },
  { name: "Rajaei Ayed", team: "Jordan" },
  { name: "Ibrahim Sadeh", team: "Jordan" },
  { name: "Mohannad Abu Taha", team: "Jordan" },
  { name: "Nizar Al Rashdan", team: "Jordan" },
  { name: "Mohammad Al Dawoud", team: "Jordan" },
  { name: "Mohammad Abu Zraiq", team: "Jordan" },
  { name: "Mousa Al Tamari", team: "Jordan" },
  { name: "Ali Olwan", team: "Jordan" },
  { name: "Odeh Fakhoury", team: "Jordan" },
  { name: "Ibrahim Sabra", team: "Jordan" },
  { name: "Ali Azaizeh", team: "Jordan" },

  // ── MEXICO (Grupo A) ───────────────────────────────────────
  { name: "Raul Rangel", team: "Mexico" },
  { name: "Guillermo Ochoa", team: "Mexico" },
  { name: "Carlos Acevedo", team: "Mexico" },
  { name: "Jorge Sanchez", team: "Mexico" },
  { name: "Israel Reyes", team: "Mexico" },
  { name: "Cesar Montes", team: "Mexico" },
  { name: "Johan Vasquez", team: "Mexico" },
  { name: "Jesus Gallardo", team: "Mexico" },
  { name: "Mateo Chavez", team: "Mexico" },
  { name: "Edson Alvarez", team: "Mexico" },
  { name: "Erik Lira", team: "Mexico" },
  { name: "Orbelin Pineda", team: "Mexico" },
  { name: "Alvaro Fidalgo", team: "Mexico" },
  { name: "Brian Gutierrez", team: "Mexico" },
  { name: "Luis Romo", team: "Mexico" },
  { name: "Obed Vargas", team: "Mexico" },
  { name: "Gilberto Mora", team: "Mexico" },
  { name: "Luis Chavez", team: "Mexico" },
  { name: "Roberto Alvarado", team: "Mexico" },
  { name: "Cesar Huerta", team: "Mexico" },
  { name: "Alexis Vega", team: "Mexico" },
  { name: "Julian Quinones", team: "Mexico" },
  { name: "Guillermo Martinez", team: "Mexico" },
  { name: "Armando Gonzalez", team: "Mexico" },
  { name: "Santiago Gimenez", team: "Mexico" },
  { name: "Raul Jimenez", team: "Mexico" },

  // ── MOROCCO (Grupo C) ──────────────────────────────────────
  { name: "Yassine Bounou", team: "Morocco" },
  { name: "Munir El Kajoui", team: "Morocco" },
  { name: "Ahmed Reda Tagnaouti", team: "Morocco" },
  { name: "Noussair Mazraoui", team: "Morocco" },
  { name: "Anas Salah-Eddine", team: "Morocco" },
  { name: "Youssef Bellammari", team: "Morocco" },
  { name: "Achraf Hakimi", team: "Morocco" },
  { name: "Zakaria El Ouahdi", team: "Morocco" },
  { name: "Nayef Aguerd", team: "Morocco" },
  { name: "Chadi Riad", team: "Morocco" },
  { name: "Redouane Halhal", team: "Morocco" },
  { name: "Issa Diop", team: "Morocco" },
  { name: "Samir El Mourabet", team: "Morocco" },
  { name: "Ayoub Bouaddi", team: "Morocco" },
  { name: "Neil El Aynaoui", team: "Morocco" },
  { name: "Sofyan Amrabat", team: "Morocco" },
  { name: "Azzedine Ounahi", team: "Morocco" },
  { name: "Bilal El Khannouss", team: "Morocco" },
  { name: "Ismael Saibari", team: "Morocco" },
  { name: "Abdesamad Ezzalzouli", team: "Morocco" },
  { name: "Chemsdine Talbi", team: "Morocco" },
  { name: "Soufiane Rahimi", team: "Morocco" },
  { name: "Ayoub El Kaabi", team: "Morocco" },
  { name: "Brahim Diaz", team: "Morocco" },
  { name: "Yassine Gessim", team: "Morocco" },
  { name: "Ayoube Amaimouni", team: "Morocco" },

  // ── NETHERLANDS (Grupo F) ──────────────────────────────────
  { name: "Mark Flekken", team: "Netherlands" },
  { name: "Robin Roefs", team: "Netherlands" },
  { name: "Bart Verbruggen", team: "Netherlands" },
  { name: "Nathan Ake", team: "Netherlands" },
  { name: "Virgil van Dijk", team: "Netherlands" },
  { name: "Denzel Dumfries", team: "Netherlands" },
  { name: "Jan Paul van Hecke", team: "Netherlands" },
  { name: "Jurrien Timber", team: "Netherlands" },
  { name: "Jorrel Hato", team: "Netherlands" },
  { name: "Micky van de Ven", team: "Netherlands" },
  { name: "Ryan Gravenberch", team: "Netherlands" },
  { name: "Frenkie de Jong", team: "Netherlands" },
  { name: "Teun Koopmeiners", team: "Netherlands" },
  { name: "Tijjani Reijnders", team: "Netherlands" },
  { name: "Marten de Roon", team: "Netherlands" },
  { name: "Guus Til", team: "Netherlands" },
  { name: "Quinten Timber", team: "Netherlands" },
  { name: "Mats Wieffer", team: "Netherlands" },
  { name: "Brian Brobbey", team: "Netherlands" },
  { name: "Memphis Depay", team: "Netherlands" },
  { name: "Cody Gakpo", team: "Netherlands" },
  { name: "Noa Lang", team: "Netherlands" },
  { name: "Donyell Malen", team: "Netherlands" },
  { name: "Crysencio Summerville", team: "Netherlands" },
  { name: "Wout Weghorst", team: "Netherlands" },
  { name: "Justin Kluivert", team: "Netherlands" },

  // ── NEW ZEALAND (Grupo G) ──────────────────────────────────
  { name: "Max Crocombe", team: "New Zealand" },
  { name: "Alex Paulsen", team: "New Zealand" },
  { name: "Michael Woud", team: "New Zealand" },
  { name: "Tyler Bindon", team: "New Zealand" },
  { name: "Michael Boxall", team: "New Zealand" },
  { name: "Liberato Cacace", team: "New Zealand" },
  { name: "Francis de Vries", team: "New Zealand" },
  { name: "Callan Elliot", team: "New Zealand" },
  { name: "Tim Payne", team: "New Zealand" },
  { name: "Nando Pijnaker", team: "New Zealand" },
  { name: "Tommy Smith", team: "New Zealand" },
  { name: "Finn Surman", team: "New Zealand" },
  { name: "Lachlan Bayliss", team: "New Zealand" },
  { name: "Joe Bell", team: "New Zealand" },
  { name: "Matt Garbett", team: "New Zealand" },
  { name: "Eli Just", team: "New Zealand" },
  { name: "Callum McCowatt", team: "New Zealand" },
  { name: "Ben Old", team: "New Zealand" },
  { name: "Alex Rufer", team: "New Zealand" },
  { name: "Marko Stamenic", team: "New Zealand" },
  { name: "Sarpreet Singh", team: "New Zealand" },
  { name: "Ryan Thomas", team: "New Zealand" },
  { name: "Kosta Barbarouses", team: "New Zealand" },
  { name: "Jesse Randall", team: "New Zealand" },
  { name: "Ben Waine", team: "New Zealand" },
  { name: "Chris Wood", team: "New Zealand" },

  // ── NORWAY (Grupo I) ───────────────────────────────────────
  { name: "Orjan Nyland", team: "Norway" },
  { name: "Egil Selvik", team: "Norway" },
  { name: "Sander Tangvik", team: "Norway" },
  { name: "Kristoffer Ajer", team: "Norway" },
  { name: "Fredrik Bjorkan", team: "Norway" },
  { name: "Henrik Falchener", team: "Norway" },
  { name: "Sondre Langas", team: "Norway" },
  { name: "Torbjorn Heggem", team: "Norway" },
  { name: "Marcus Holmgren Pedersen", team: "Norway" },
  { name: "Julian Ryerson", team: "Norway" },
  { name: "David Moller Wolfe", team: "Norway" },
  { name: "Leo Ostigard", team: "Norway" },
  { name: "Thelonious Aasgaard", team: "Norway" },
  { name: "Fredrik Aursnes", team: "Norway" },
  { name: "Patrick Berg", team: "Norway" },
  { name: "Sander Berge", team: "Norway" },
  { name: "Oscar Bobb", team: "Norway" },
  { name: "Jens Petter Hauge", team: "Norway" },
  { name: "Antonio Nusa", team: "Norway" },
  { name: "Andreas Schjelderup", team: "Norway" },
  { name: "Morten Thorsby", team: "Norway" },
  { name: "Kristian Thorstvedt", team: "Norway" },
  { name: "Martin Odegaard", team: "Norway" },
  { name: "Erling Haaland", team: "Norway" },
  { name: "Alexander Sorloth", team: "Norway" },
  { name: "Jorgen Strand Larsen", team: "Norway" },

  // ── PANAMA (Grupo L) ───────────────────────────────────────
  { name: "Orlando Mosquera", team: "Panama" },
  { name: "Luis Mejia", team: "Panama" },
  { name: "Cesar Samudio", team: "Panama" },
  { name: "Cesar Blackman", team: "Panama" },
  { name: "Jorge Gutierrez", team: "Panama" },
  { name: "Amir Murillo", team: "Panama" },
  { name: "Fidel Escobar", team: "Panama" },
  { name: "Andres Andrade", team: "Panama" },
  { name: "Edgardo Farina", team: "Panama" },
  { name: "Jose Cordoba", team: "Panama" },
  { name: "Eric Davis", team: "Panama" },
  { name: "Jiovany Ramos", team: "Panama" },
  { name: "Roderick Miller", team: "Panama" },
  { name: "Anibal Godoy", team: "Panama" },
  { name: "Adalberto Carrasquilla", team: "Panama" },
  { name: "Carlos Harvey", team: "Panama" },
  { name: "Cristian Martinez", team: "Panama" },
  { name: "Jose Luis Rodriguez", team: "Panama" },
  { name: "Cesar Yanis", team: "Panama" },
  { name: "Yoel Barcenas", team: "Panama" },
  { name: "Alberto Quintero", team: "Panama" },
  { name: "Azarias Londono", team: "Panama" },
  { name: "Ismael Diaz", team: "Panama" },
  { name: "Cecilio Waterman", team: "Panama" },
  { name: "Jose Fajardo", team: "Panama" },
  { name: "Tomas Rodriguez", team: "Panama" },

  // ── PARAGUAY (Grupo D) ─────────────────────────────────────
  { name: "Orlando Gill", team: "Paraguay" },
  { name: "Roberto Fernandez", team: "Paraguay" },
  { name: "Gaston Olveira", team: "Paraguay" },
  { name: "Juan Caceres", team: "Paraguay" },
  { name: "Gustavo Velazquez", team: "Paraguay" },
  { name: "Gustavo Gomez", team: "Paraguay" },
  { name: "Junior Alonso", team: "Paraguay" },
  { name: "Jose Canale", team: "Paraguay" },
  { name: "Omar Alderete", team: "Paraguay" },
  { name: "Alexandro Maidana", team: "Paraguay" },
  { name: "Fabian Balbuena", team: "Paraguay" },
  { name: "Diego Gomez", team: "Paraguay" },
  { name: "Mauricio Magalhaes", team: "Paraguay" },
  { name: "Damian Bobadilla", team: "Paraguay" },
  { name: "Braian Ojeda", team: "Paraguay" },
  { name: "Andres Cubas", team: "Paraguay" },
  { name: "Matias Galarza", team: "Paraguay" },
  { name: "Alejandro Gamarra", team: "Paraguay" },
  { name: "Gustavo Caballero", team: "Paraguay" },
  { name: "Ramon Sosa", team: "Paraguay" },
  { name: "Alex Arce", team: "Paraguay" },
  { name: "Isidro Pitta", team: "Paraguay" },
  { name: "Gabriel Avalos", team: "Paraguay" },
  { name: "Miguel Almiron", team: "Paraguay" },
  { name: "Julio Enciso", team: "Paraguay" },
  { name: "Antonio Sanabria", team: "Paraguay" },

  // ── PORTUGAL (Grupo K) ─────────────────────────────────────
  { name: "Diogo Costa", team: "Portugal" },
  { name: "Jose Sa", team: "Portugal" },
  { name: "Rui Silva", team: "Portugal" },
  { name: "Tomas Araujo", team: "Portugal" },
  { name: "Joao Cancelo", team: "Portugal" },
  { name: "Diogo Dalot", team: "Portugal" },
  { name: "Ruben Dias", team: "Portugal" },
  { name: "Goncalo Inacio", team: "Portugal" },
  { name: "Nuno Mendes", team: "Portugal" },
  { name: "Matheus Nunes", team: "Portugal" },
  { name: "Nelson Semedo", team: "Portugal" },
  { name: "Renato Veiga", team: "Portugal" },
  { name: "Samuel Costa", team: "Portugal" },
  { name: "Bruno Fernandes", team: "Portugal" },
  { name: "Joao Neves", team: "Portugal" },
  { name: "Ruben Neves", team: "Portugal" },
  { name: "Bernardo Silva", team: "Portugal" },
  { name: "Vitinha", team: "Portugal" },
  { name: "Francisco Conceicao", team: "Portugal" },
  { name: "Joao Felix", team: "Portugal" },
  { name: "Goncalo Guedes", team: "Portugal" },
  { name: "Rafael Leao", team: "Portugal" },
  { name: "Pedro Neto", team: "Portugal" },
  { name: "Goncalo Ramos", team: "Portugal" },
  { name: "Cristiano Ronaldo", team: "Portugal" },
  { name: "Francisco Trincao", team: "Portugal" },

  // ── QATAR (Grupo B) ────────────────────────────────────────
  { name: "Salah Zakaria", team: "Qatar" },
  { name: "Meshaal Barsham", team: "Qatar" },
  { name: "Mahmoud Abunada", team: "Qatar" },
  { name: "Boualem Khoukhi", team: "Qatar" },
  { name: "Pedro Miguel", team: "Qatar" },
  { name: "Sultan Al Brake", team: "Qatar" },
  { name: "Al-Hashmi Al-Hussain", team: "Qatar" },
  { name: "Ayoub Al-Alawi", team: "Qatar" },
  { name: "Issa Laye", team: "Qatar" },
  { name: "Lucas Mendes", team: "Qatar" },
  { name: "Homam Al-Amin", team: "Qatar" },
  { name: "Ahmed Fathi", team: "Qatar" },
  { name: "Jassim Gaber", team: "Qatar" },
  { name: "Assim Madibo", team: "Qatar" },
  { name: "Abdulaziz Hatem", team: "Qatar" },
  { name: "Karim Boudiaf", team: "Qatar" },
  { name: "Mohammed Mannai", team: "Qatar" },
  { name: "Almoez Ali", team: "Qatar" },
  { name: "Akram Afif", team: "Qatar" },
  { name: "Tahsin Mohammed", team: "Qatar" },
  { name: "Edmilson Junior", team: "Qatar" },
  { name: "Ahmed Al-Janehi", team: "Qatar" },
  { name: "Hassan Al Haydos", team: "Qatar" },
  { name: "Mohammed Muntari", team: "Qatar" },
  { name: "Yusuf Abdurisag", team: "Qatar" },

  // ── SAUDI ARABIA (Grupo H) ─────────────────────────────────
  { name: "Nawaf Al Aqidi", team: "Saudi Arabia" },
  { name: "Mohamed Al Owais", team: "Saudi Arabia" },
  { name: "Ahmed Alkassar", team: "Saudi Arabia" },
  { name: "Saud Abdulhamid", team: "Saudi Arabia" },
  { name: "Jehad Thakri", team: "Saudi Arabia" },
  { name: "Abdulelah Al Amri", team: "Saudi Arabia" },
  { name: "Hassan Tambakti", team: "Saudi Arabia" },
  { name: "Ali Lajami", team: "Saudi Arabia" },
  { name: "Hassan Kadesh", team: "Saudi Arabia" },
  { name: "Moteb Al Harbi", team: "Saudi Arabia" },
  { name: "Nawaf Boushal", team: "Saudi Arabia" },
  { name: "Ali Majrashi", team: "Saudi Arabia" },
  { name: "Mohammed Abu Alshamat", team: "Saudi Arabia" },
  { name: "Sultan Al-Ghannam", team: "Saudi Arabia" },
  { name: "Ziyad Al Johani", team: "Saudi Arabia" },
  { name: "Nasser Al Dawsari", team: "Saudi Arabia" },
  { name: "Mohamed Kanno", team: "Saudi Arabia" },
  { name: "Abdullah Al Khaibari", team: "Saudi Arabia" },
  { name: "Alaa Al Hejji", team: "Saudi Arabia" },
  { name: "Musab Al Juwayr", team: "Saudi Arabia" },
  { name: "Khalid Al Ghannam", team: "Saudi Arabia" },
  { name: "Ayman Yahya", team: "Saudi Arabia" },
  { name: "Salem Al Dawsari", team: "Saudi Arabia" },
  { name: "Abdullah Al Hamdan", team: "Saudi Arabia" },
  { name: "Firas Al Buraikan", team: "Saudi Arabia" },
  { name: "Saleh Al Shehri", team: "Saudi Arabia" },

  // ── SCOTLAND (Grupo C) ─────────────────────────────────────
  { name: "Craig Gordon", team: "Scotland" },
  { name: "Angus Gunn", team: "Scotland" },
  { name: "Liam Kelly", team: "Scotland" },
  { name: "Grant Hanley", team: "Scotland" },
  { name: "Jack Hendry", team: "Scotland" },
  { name: "Aaron Hickey", team: "Scotland" },
  { name: "Dom Hyam", team: "Scotland" },
  { name: "Scott McKenna", team: "Scotland" },
  { name: "Nathan Patterson", team: "Scotland" },
  { name: "Anthony Ralston", team: "Scotland" },
  { name: "Andy Robertson", team: "Scotland" },
  { name: "John Souttar", team: "Scotland" },
  { name: "Kieran Tierney", team: "Scotland" },
  { name: "Ryan Christie", team: "Scotland" },
  { name: "Findlay Curtis", team: "Scotland" },
  { name: "Lewis Ferguson", team: "Scotland" },
  { name: "Ben Doak", team: "Scotland" },
  { name: "John McGinn", team: "Scotland" },
  { name: "Kenny McLean", team: "Scotland" },
  { name: "Scott McTominay", team: "Scotland" },
  { name: "Che Adams", team: "Scotland" },
  { name: "Lyndon Dykes", team: "Scotland" },
  { name: "George Hirst", team: "Scotland" },
  { name: "Lawrence Shankland", team: "Scotland" },
  { name: "Ross Stewart", team: "Scotland" },

  // ── SENEGAL (Grupo I) ──────────────────────────────────────
  { name: "Edouard Mendy", team: "Senegal" },
  { name: "Mory Diaw", team: "Senegal" },
  { name: "Yehvann Diouf", team: "Senegal" },
  { name: "Krepin Diatta", team: "Senegal" },
  { name: "Antoine Mendy", team: "Senegal" },
  { name: "Kalidou Koulibaly", team: "Senegal" },
  { name: "El Hadji Malick Diouf", team: "Senegal" },
  { name: "Mamadou Sarr", team: "Senegal" },
  { name: "Moussa Niakhate", team: "Senegal" },
  { name: "Abdoulaye Seck", team: "Senegal" },
  { name: "Ismail Jakobs", team: "Senegal" },
  { name: "Idrissa Gana Gueye", team: "Senegal" },
  { name: "Pape Gueye", team: "Senegal" },
  { name: "Lamine Camara", team: "Senegal" },
  { name: "Habib Diarra", team: "Senegal" },
  { name: "Pathe Ciss", team: "Senegal" },
  { name: "Pape Matar Sarr", team: "Senegal" },
  { name: "Bara Ndiaye", team: "Senegal" },
  { name: "Sadio Mane", team: "Senegal" },
  { name: "Ismaila Sarr", team: "Senegal" },
  { name: "Iliman Ndiaye", team: "Senegal" },
  { name: "Assane Diao", team: "Senegal" },
  { name: "Ibrahim Mbaye", team: "Senegal" },
  { name: "Nicolas Jackson", team: "Senegal" },
  { name: "Bamba Dieng", team: "Senegal" },
  { name: "Cherif Ndiaye", team: "Senegal" },

  // ── SOUTH AFRICA (Grupo A) ─────────────────────────────────
  { name: "Ronwen Williams", team: "South Africa" },
  { name: "Ricardo Goss", team: "South Africa" },
  { name: "Sipho Chaine", team: "South Africa" },
  { name: "Aubrey Modiba", team: "South Africa" },
  { name: "Khuliso Mudau", team: "South Africa" },
  { name: "Khulumani Ndamane", team: "South Africa" },
  { name: "Kamogelo Sebelebele", team: "South Africa" },
  { name: "Nkosinathi Sibisi", team: "South Africa" },
  { name: "Bradley Cross", team: "South Africa" },
  { name: "Samukele Kabini", team: "South Africa" },
  { name: "Olwethu Makhanya", team: "South Africa" },
  { name: "Thabang Matuludi", team: "South Africa" },
  { name: "Mbekezeli Mbokazi", team: "South Africa" },
  { name: "Ime Okon", team: "South Africa" },
  { name: "Oswin Appollis", team: "South Africa" },
  { name: "Thalente Mbatha", team: "South Africa" },
  { name: "Relebohile Mofokeng", team: "South Africa" },
  { name: "Jayden Adams", team: "South Africa" },
  { name: "Teboho Mokoena", team: "South Africa" },
  { name: "Themba Zwane", team: "South Africa" },
  { name: "Sphephelo Sithole", team: "South Africa" },
  { name: "Evidence Makgopa", team: "South Africa" },
  { name: "Tshepang Moremi", team: "South Africa" },
  { name: "Lyle Foster", team: "South Africa" },
  { name: "Thapelo Maseko", team: "South Africa" },
  { name: "Iqraam Rayners", team: "South Africa" },

  // ── SOUTH KOREA (Grupo A) ──────────────────────────────────
  { name: "Song Bumkeun", team: "South Korea" },
  { name: "Jo Hyeonwoo", team: "South Korea" },
  { name: "Kim Seung-gyu", team: "South Korea" },
  { name: "Jens Castrop", team: "South Korea" },
  { name: "Lee Hanbeom", team: "South Korea" },
  { name: "Park Jinseob", team: "South Korea" },
  { name: "Lee Kihyuk", team: "South Korea" },
  { name: "Kim Minjae", team: "South Korea" },
  { name: "Kim Moonhwan", team: "South Korea" },
  { name: "Kim Taehyeon", team: "South Korea" },
  { name: "Lee Taeseok", team: "South Korea" },
  { name: "Seol Youngwoo", team: "South Korea" },
  { name: "Cho Wije", team: "South Korea" },
  { name: "Lee Donggyeong", team: "South Korea" },
  { name: "Hwang Heechan", team: "South Korea" },
  { name: "Yang Hyunjun", team: "South Korea" },
  { name: "Hwang Inbeom", team: "South Korea" },
  { name: "Lee Jaesung", team: "South Korea" },
  { name: "Kim Jingyu", team: "South Korea" },
  { name: "Eom Jisung", team: "South Korea" },
  { name: "Bae Junho", team: "South Korea" },
  { name: "Lee Kangin", team: "South Korea" },
  { name: "Paik Seungho", team: "South Korea" },
  { name: "Cho Guesung", team: "South Korea" },
  { name: "Son Heungmin", team: "South Korea" },
  { name: "Oh Hyeongyu", team: "South Korea" },

  // ── SPAIN (Grupo H) ────────────────────────────────────────
  { name: "Unai Simon", team: "Spain" },
  { name: "David Raya", team: "Spain" },
  { name: "Joan Garcia", team: "Spain" },
  { name: "Marc Cucurella", team: "Spain" },
  { name: "Pau Cubarsi", team: "Spain" },
  { name: "Aymeric Laporte", team: "Spain" },
  { name: "Alejandro Grimaldo", team: "Spain" },
  { name: "Pedro Porro", team: "Spain" },
  { name: "Eric Garcia", team: "Spain" },
  { name: "Marcos Llorente", team: "Spain" },
  { name: "Marc Pubill", team: "Spain" },
  { name: "Gavi", team: "Spain" },
  { name: "Rodri", team: "Spain" },
  { name: "Pedri", team: "Spain" },
  { name: "Martin Zubimendi", team: "Spain" },
  { name: "Fabian Ruiz", team: "Spain" },
  { name: "Alex Baena", team: "Spain" },
  { name: "Mikel Merino", team: "Spain" },
  { name: "Lamine Yamal", team: "Spain" },
  { name: "Nico Williams", team: "Spain" },
  { name: "Dani Olmo", team: "Spain" },
  { name: "Ferran Torres", team: "Spain" },
  { name: "Mikel Oyarzabal", team: "Spain" },
  { name: "Yeremy Pino", team: "Spain" },
  { name: "Borja Iglesias", team: "Spain" },
  { name: "Victor Munoz", team: "Spain" },

  // ── SWEDEN (Grupo F) ───────────────────────────────────────
  { name: "Viktor Johansson", team: "Sweden" },
  { name: "Kristoffer Nordfeldt", team: "Sweden" },
  { name: "Jacob Zetterstrom", team: "Sweden" },
  { name: "Hjalmar Ekdal", team: "Sweden" },
  { name: "Gabriel Gudmundsson", team: "Sweden" },
  { name: "Isak Hien", team: "Sweden" },
  { name: "Victor Lindelof", team: "Sweden" },
  { name: "Eric Smith", team: "Sweden" },
  { name: "Carl Starfelt", team: "Sweden" },
  { name: "Daniel Svensson", team: "Sweden" },
  { name: "Yasin Ayari", team: "Sweden" },
  { name: "Lucas Bergvall", team: "Sweden" },
  { name: "Jesper Karlstrom", team: "Sweden" },
  { name: "Benjamin Nygren", team: "Sweden" },
  { name: "Ken Sema", team: "Sweden" },
  { name: "Elliot Stroud", team: "Sweden" },
  { name: "Mattias Svanberg", team: "Sweden" },
  { name: "Besfort Zeneli", team: "Sweden" },
  { name: "Alexander Bernhardsson", team: "Sweden" },
  { name: "Anthony Elanga", team: "Sweden" },
  { name: "Viktor Gyokeres", team: "Sweden" },
  { name: "Alexander Isak", team: "Sweden" },
  { name: "Gustaf Nilsson", team: "Sweden" },

  // ── SWITZERLAND (Grupo B) ──────────────────────────────────
  { name: "Marvin Keller", team: "Switzerland" },
  { name: "Gregor Kobel", team: "Switzerland" },
  { name: "Yvon Mvogo", team: "Switzerland" },
  { name: "Manuel Akanji", team: "Switzerland" },
  { name: "Aurele Amenda", team: "Switzerland" },
  { name: "Eray Comert", team: "Switzerland" },
  { name: "Nico Elvedi", team: "Switzerland" },
  { name: "Luca Jaquez", team: "Switzerland" },
  { name: "Miro Muheim", team: "Switzerland" },
  { name: "Ricardo Rodriguez", team: "Switzerland" },
  { name: "Silvan Widmer", team: "Switzerland" },
  { name: "Michel Aebischer", team: "Switzerland" },
  { name: "Christian Fassnacht", team: "Switzerland" },
  { name: "Remo Freuler", team: "Switzerland" },
  { name: "Ardon Jashari", team: "Switzerland" },
  { name: "Fabian Rieder", team: "Switzerland" },
  { name: "Djibril Sow", team: "Switzerland" },
  { name: "Cedric Itten", team: "Switzerland" },
  { name: "Granit Xhaka", team: "Switzerland" },
  { name: "Denis Zakaria", team: "Switzerland" },
  { name: "Ruben Vargas", team: "Switzerland" },
  { name: "Zeki Amdouni", team: "Switzerland" },
  { name: "Breel Embolo", team: "Switzerland" },
  { name: "Dan Ndoye", team: "Switzerland" },
  { name: "Noah Okafor", team: "Switzerland" },
  { name: "Johan Manzambi", team: "Switzerland" },

  // ── TUNISIA (Grupo F) ──────────────────────────────────────
  { name: "Sabri Ben Hessen", team: "Tunisia" },
  { name: "Abdelmouhib Chamakh", team: "Tunisia" },
  { name: "Aymen Dahman", team: "Tunisia" },
  { name: "Ali Abdi", team: "Tunisia" },
  { name: "Adem Arous", team: "Tunisia" },
  { name: "Mohamed Amine Ben Hamida", team: "Tunisia" },
  { name: "Dylan Bronn", team: "Tunisia" },
  { name: "Raed Chikhaoui", team: "Tunisia" },
  { name: "Moutaz Neffati", team: "Tunisia" },
  { name: "Omar Rekik", team: "Tunisia" },
  { name: "Montassar Talbi", team: "Tunisia" },
  { name: "Yan Valery", team: "Tunisia" },
  { name: "Mortadha Ben Ouanes", team: "Tunisia" },
  { name: "Anis Ben Slimane", team: "Tunisia" },
  { name: "Ismael Gharbi", team: "Tunisia" },
  { name: "Rani Khedira", team: "Tunisia" },
  { name: "Hannibal Mejbri", team: "Tunisia" },
  { name: "Ellyes Skhiri", team: "Tunisia" },
  { name: "Elias Achouri", team: "Tunisia" },
  { name: "Khalil Ayari", team: "Tunisia" },
  { name: "Firas Chaouat", team: "Tunisia" },
  { name: "Rayan Elloumi", team: "Tunisia" },
  { name: "Hazem Mastouri", team: "Tunisia" },
  { name: "Elias Saad", team: "Tunisia" },
  { name: "Sebastian Tounekti", team: "Tunisia" },

  // ── TURKEY (Grupo D) ───────────────────────────────────────
  { name: "Altay Bayindir", team: "Turkey" },
  { name: "Mert Gunok", team: "Turkey" },
  { name: "Ugurcan Cakir", team: "Turkey" },
  { name: "Abdulkerim Bardakci", team: "Turkey" },
  { name: "Caglar Soyuncu", team: "Turkey" },
  { name: "Eren Elmali", team: "Turkey" },
  { name: "Ferdi Kadioglu", team: "Turkey" },
  { name: "Merih Demiral", team: "Turkey" },
  { name: "Mert Muldur", team: "Turkey" },
  { name: "Ozan Kabak", team: "Turkey" },
  { name: "Samet Akaydin", team: "Turkey" },
  { name: "Zeki Celik", team: "Turkey" },
  { name: "Hakan Calhanoglu", team: "Turkey" },
  { name: "Ismail Yuksek", team: "Turkey" },
  { name: "Kaan Ayhan", team: "Turkey" },
  { name: "Orkun Kokcu", team: "Turkey" },
  { name: "Salih Ozcan", team: "Turkey" },
  { name: "Arda Guler", team: "Turkey" },
  { name: "Baris Alper Yilmaz", team: "Turkey" },
  { name: "Can Uzun", team: "Turkey" },
  { name: "Deniz Gul", team: "Turkey" },
  { name: "Irfan Can Kahveci", team: "Turkey" },
  { name: "Kenan Yildiz", team: "Turkey" },
  { name: "Kerem Akturkoglu", team: "Turkey" },
  { name: "Oguz Aydin", team: "Turkey" },
  { name: "Yunus Akgun", team: "Turkey" },

  // ── UNITED STATES (Grupo D) ────────────────────────────────
  { name: "Chris Brady", team: "United States" },
  { name: "Matt Freese", team: "United States" },
  { name: "Matt Turner", team: "United States" },
  { name: "Max Arfsten", team: "United States" },
  { name: "Sergino Dest", team: "United States" },
  { name: "Alex Freeman", team: "United States" },
  { name: "Mark McKenzie", team: "United States" },
  { name: "Tim Ream", team: "United States" },
  { name: "Chris Richards", team: "United States" },
  { name: "Antonee Robinson", team: "United States" },
  { name: "Miles Robinson", team: "United States" },
  { name: "Joe Scally", team: "United States" },
  { name: "Auston Trusty", team: "United States" },
  { name: "Tyler Adams", team: "United States" },
  { name: "Sebastian Berhalter", team: "United States" },
  { name: "Weston McKennie", team: "United States" },
  { name: "Cristian Roldan", team: "United States" },
  { name: "Brenden Aaronson", team: "United States" },
  { name: "Christian Pulisic", team: "United States" },
  { name: "Gio Reyna", team: "United States" },
  { name: "Malik Tillman", team: "United States" },
  { name: "Tim Weah", team: "United States" },
  { name: "Alejandro Zendejas", team: "United States" },
  { name: "Folarin Balogun", team: "United States" },
  { name: "Ricardo Pepi", team: "United States" },
  { name: "Haji Wright", team: "United States" },

  // ── URUGUAY (Grupo H) ──────────────────────────────────────
  { name: "Sergio Rochet", team: "Uruguay" },
  { name: "Fernando Muslera", team: "Uruguay" },
  { name: "Santiago Mele", team: "Uruguay" },
  { name: "Guillermo Varela", team: "Uruguay" },
  { name: "Ronald Araujo", team: "Uruguay" },
  { name: "Jose Maria Gimenez", team: "Uruguay" },
  { name: "Santiago Bueno", team: "Uruguay" },
  { name: "Sebastian Caceres", team: "Uruguay" },
  { name: "Mathias Olivera", team: "Uruguay" },
  { name: "Joaquin Piquerez", team: "Uruguay" },
  { name: "Matias Vina", team: "Uruguay" },
  { name: "Juan Manuel Sanabria", team: "Uruguay" },
  { name: "Federico Valverde", team: "Uruguay" },
  { name: "Rodrigo Bentancur", team: "Uruguay" },
  { name: "Manuel Ugarte", team: "Uruguay" },
  { name: "Emiliano Martinez", team: "Uruguay" },
  { name: "Rodrigo Zalazar", team: "Uruguay" },
  { name: "Giorgian de Arrascaeta", team: "Uruguay" },
  { name: "Nicolas de la Cruz", team: "Uruguay" },
  { name: "Agustin Canobbio", team: "Uruguay" },
  { name: "Maximiliano Araujo", team: "Uruguay" },
  { name: "Brian Rodriguez", team: "Uruguay" },
  { name: "Facundo Pellistri", team: "Uruguay" },
  { name: "Darwin Nunez", team: "Uruguay" },
  { name: "Federico Vinas", team: "Uruguay" },
  { name: "Rodrigo Aguirre", team: "Uruguay" },

  // ── UZBEKISTAN (Grupo K) ───────────────────────────────────
  { name: "Botirali Ergashev", team: "Uzbekistan" },
  { name: "Abduvohid Nematov", team: "Uzbekistan" },
  { name: "Utkir Yusupov", team: "Uzbekistan" },
  { name: "Abdukodir Khusanov", team: "Uzbekistan" },
  { name: "Khojiakbar Alijonov", team: "Uzbekistan" },
  { name: "Rustamjon Ashurmatov", team: "Uzbekistan" },
  { name: "Farrukh Sayfiev", team: "Uzbekistan" },
  { name: "Sherzod Nasrullaev", team: "Uzbekistan" },
  { name: "Umarbek Eshmuradov", team: "Uzbekistan" },
  { name: "Avazbek Ulmasaliev", team: "Uzbekistan" },
  { name: "Jakhongir Urozov", team: "Uzbekistan" },
  { name: "Bekhruz Karimov", team: "Uzbekistan" },
  { name: "Abdulla Abdullaev", team: "Uzbekistan" },
  { name: "Sherzod Esanov", team: "Uzbekistan" },
  { name: "Akmal Mozgovoy", team: "Uzbekistan" },
  { name: "Otabek Shukurov", team: "Uzbekistan" },
  { name: "Jamshid Iskanderov", team: "Uzbekistan" },
  { name: "Azizbek Ganiev", team: "Uzbekistan" },
  { name: "Abbosbek Fayzullaev", team: "Uzbekistan" },
  { name: "Jaloliddin Masharipov", team: "Uzbekistan" },
  { name: "Dostonbek Khamdamov", team: "Uzbekistan" },
  { name: "Umarali Rakhmonaliev", team: "Uzbekistan" },
  { name: "Oston Urunov", team: "Uzbekistan" },
  { name: "Azizbek Amonov", team: "Uzbekistan" },
  { name: "Eldor Shomurodov", team: "Uzbekistan" },
  { name: "Igor Sergeev", team: "Uzbekistan" },
];
