// Traduce los nombres de equipos que TheSportsDB devuelve en inglés al español.
// Se usa solo para display — la DB sigue guardando el nombre en inglés.
const EN_TO_ES: Record<string, string> = {
  // Sudamérica
  Brazil: "Brasil",
  Peru: "Perú",
  Paraguay: "Paraguay",
  // Concacaf
  Mexico: "México",
  "United States": "Estados Unidos",
  USA: "Estados Unidos",
  Canada: "Canadá",
  Haiti: "Haití",
  Panama: "Panamá",
  Curacao: "Curazao",
  "Trinidad and Tobago": "Trinidad y Tobago",
  Honduras: "Honduras",
  "Costa Rica": "Costa Rica",
  Jamaica: "Jamaica",
  "El Salvador": "El Salvador",
  Cuba: "Cuba",
  // Europa
  Germany: "Alemania",
  France: "Francia",
  Spain: "España",
  England: "Inglaterra",
  Scotland: "Escocia",
  Wales: "Gales",
  Netherlands: "Países Bajos",
  Belgium: "Bélgica",
  Croatia: "Croacia",
  Switzerland: "Suiza",
  Poland: "Polonia",
  Denmark: "Dinamarca",
  Sweden: "Suecia",
  Turkey: "Turquía",
  Greece: "Grecia",
  Norway: "Noruega",
  "Czech Republic": "República Checa",
  Czechia: "República Checa",
  Ukraine: "Ucrania",
  Hungary: "Hungría",
  Romania: "Rumanía",
  Slovakia: "Eslovaquia",
  Slovenia: "Eslovenia",
  "Bosnia-Herzegovina": "Bosnia y Herzegovina",
  "Bosnia and Herzegovina": "Bosnia y Herzegovina",
  "North Macedonia": "Macedonia del Norte",
  Albania: "Albania",
  Georgia: "Georgia",
  Austria: "Austria",
  Serbia: "Serbia",
  Portugal: "Portugal",
  Italy: "Italia",
  // África
  Morocco: "Marruecos",
  "Ivory Coast": "Costa de Marfil",
  Cameroon: "Camerún",
  Egypt: "Egipto",
  Tunisia: "Túnez",
  Algeria: "Argelia",
  "South Africa": "Sudáfrica",
  "DR Congo": "R.D. del Congo",
  "Cape Verde": "Cabo Verde",
  Senegal: "Senegal",
  Ghana: "Ghana",
  Nigeria: "Nigeria",
  Mali: "Malí",
  Zambia: "Zambia",
  Tanzania: "Tanzania",
  Angola: "Angola",
  Gabon: "Gabón",
  Guinea: "Guinea",
  Kenya: "Kenia",
  Mozambique: "Mozambique",
  // Asia / Oceanía
  Japan: "Japón",
  "South Korea": "Corea del Sur",
  "Saudi Arabia": "Arabia Saudí",
  Iran: "Irán",
  Qatar: "Catar",
  Australia: "Australia",
  "New Zealand": "Nueva Zelanda",
  Uzbekistan: "Uzbekistán",
  Jordan: "Jordania",
  Iraq: "Irak",
  China: "China",
  Indonesia: "Indonesia",
  Thailand: "Tailandia",
  Bahrain: "Baréin",
  Palestine: "Palestina",
  Syria: "Siria",
  Lebanon: "Líbano",
  Tajikistan: "Tayikistán",
};

export function toSpanish(name: string): string {
  return EN_TO_ES[name] ?? name;
}
